[control_plane]
k8s-master ansible_host=10.0.1.10 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[worker_nodes]
k8s-worker-01 ansible_host=10.0.1.11 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa
k8s-worker-02 ansible_host=10.0.1.12 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa
k8s-worker-03 ansible_host=10.0.1.13 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[monitoring_nodes]
monitoring ansible_host=10.0.1.20 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[k8s_cluster:children]
control_plane
worker_nodes

[all:children]
k8s_cluster
monitoring_nodes
