- name: Restart prometheus
  community.docker.docker_compose_v2:
    project_src: /opt/monitoring
    services:
      - prometheus
    state: restarted
  become: true

- name: Restart alertmanager
  community.docker.docker_compose_v2:
    project_src: /opt/monitoring
    services:
      - alertmanager
    state: restarted
  become: true