name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
      - name: SSH -> server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "SSH connection successful"
            hostname
            whoami

      - name: Update project on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e
            cd ~/app
            git fetch origin
            git reset --hard origin/main
        
      - name: Run Ansible
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e

            echo "Installing Ansible if missing..."
            if ! command -v ansible-playbook >/dev/null 2>&1; then
              sudo apt update
              sudo apt install -y ansible
            fi

            echo "Entering Ansible folder..."
            cd ~/app/ansible

            echo "Creating vault password file..."
            echo "${{ secrets.ANSIBLE_VAULT_PASS }}" > /tmp/vault_pass.txt
            chmod 600 /tmp/vault_pass.txt

            echo "Running Ansible playbook..."
            ansible-playbook site.yml \
              -i inventory/hosts.ini \
              --vault-password-file /tmp/vault_pass.txt

            echo "Cleaning up..."
            rm -f /tmp/vault_pass.txt

            echo "Ansible finished successfully"

      - name: Build images
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e
            cd ~/app

            docker build -t microshop/auth-service:latest ./services/auth
            docker build -t microshop/user-service:latest ./services/user
            docker build -t microshop/product-service:latest ./services/product
            docker build -t microshop/order-service:latest ./services/order
            docker build -t microshop/chat-service:latest ./services/chat
            docker build -t microshop/review-service:latest ./services/review
            docker build -t microshop/frontend:latest ./frontend

      - name: Deploy kube
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e
            cd ~/app

            docker save microshop/auth-service:latest | sudo k3s ctr images import -
            docker save microshop/user-service:latest | sudo k3s ctr images import -
            docker save microshop/product-service:latest | sudo k3s ctr images import -
            docker save microshop/order-service:latest | sudo k3s ctr images import -
            docker save microshop/chat-service:latest | sudo k3s ctr images import -
            docker save microshop/review-service:latest | sudo k3s ctr images import -
            docker save microshop/frontend:latest | sudo k3s ctr images import -

            sudo k3s kubectl apply -f k8s/

      # - name: Testing
      #   uses: appleboy/ssh-action@v1.0.3
      #   with:
      #     host: ${{ secrets.SERVER_HOST }}
      #     username: ${{ secrets.SERVER_USER }}
      #     key: ${{ secrets.SERVER_SSH_KEY }}
      #     script: |
      #       set -e

      #       sudo k3s kubectl get nodes
      #       sudo k3s kubectl get pods -A
      #       sudo k3s kubectl get svc -A

      #       curl -I http://localhost || true

      #       echo "CI/CD finished successfully"
      - name: Testing
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e

            echo "Checking Kubernetes node..."
            sudo k3s kubectl get nodes

            echo "Checking microshop pods..."
            sudo k3s kubectl get pods -n microshop

            echo "Waiting for microshop pods to be ready..."
            sudo k3s kubectl wait --for=condition=Ready pod --all -n microshop --timeout=120s

            echo "Checking microshop services..."
            sudo k3s kubectl get svc -n microshop

            echo "Testing Kubernetes DNS..."
            sudo k3s kubectl exec -n microshop deploy/auth-service -- getent hosts postgres-identity

            echo "Testing frontend..."
            curl -I http://localhost || true

            echo "CI/CD finished successfully"